version: '3.3'

services:
  db:
    build: ./src/database/
    container_name: nutri-mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    networks:
      - nutri-network
    volumes:
      - ./src/database/sql.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    depends_on:
      - db
    build: ./
    ports:
      - "3333:3333"
    restart: always
    networks:
      - nutri-network

networks:
  nutri-network: